/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Legion
 */
public class PatientInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientInfoPanel
     */
    public PatientInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exudateGroup = new javax.swing.ButtonGroup();
        buttonPanel = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        questionsPanels = new javax.swing.JPanel();
        feverLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        exhudateYesButton = new javax.swing.JRadioButton();
        exhudateNoButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        YesButton = new javax.swing.JRadioButton();
        exhudateNoButton1 = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        buttonPanel.setMaximumSize(new java.awt.Dimension(100, 50));
        buttonPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(504, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nextButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        feverLabel.setText("Does the patient have fever?");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Mild", "No" }));

        exudateGroup.add(exhudateYesButton);
        exhudateYesButton.setText("Yes");

        exudateGroup.add(exhudateNoButton);
        exhudateNoButton.setText("No");

        jLabel1.setText("Does the patient present exhudate?");

        exudateGroup.add(YesButton);
        YesButton.setText("Yes");

        exudateGroup.add(exhudateNoButton1);
        exhudateNoButton1.setText("No");

        javax.swing.GroupLayout questionsPanelsLayout = new javax.swing.GroupLayout(questionsPanels);
        questionsPanels.setLayout(questionsPanelsLayout);
        questionsPanelsLayout.setHorizontalGroup(
            questionsPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionsPanelsLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(questionsPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feverLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(questionsPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionsPanelsLayout.createSequentialGroup()
                        .addComponent(exhudateYesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exhudateNoButton))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(questionsPanelsLayout.createSequentialGroup()
                        .addComponent(YesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exhudateNoButton1)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        questionsPanelsLayout.setVerticalGroup(
            questionsPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionsPanelsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(questionsPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feverLabel)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionsPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exhudateYesButton)
                    .addComponent(exhudateNoButton)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(questionsPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exhudateNoButton1)
                    .addComponent(YesButton))
                .addContainerGap(264, Short.MAX_VALUE))
        );

        add(questionsPanels, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton YesButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JRadioButton exhudateNoButton;
    private javax.swing.JRadioButton exhudateNoButton1;
    private javax.swing.JRadioButton exhudateYesButton;
    private javax.swing.ButtonGroup exudateGroup;
    private javax.swing.JLabel feverLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextButton;
    private javax.swing.JPanel questionsPanels;
    // End of variables declaration//GEN-END:variables
}
